/** @type {import('tailwindcss').Config} */
import colorConfig from './src/config/colorConfig';

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: colorConfig.primary[700],
        'primary-50': colorConfig.primary[50],
        'primary-100': colorConfig.primary[100],
        'primary-200': colorConfig.primary[200],
        'primary-300': colorConfig.primary[300],
        'primary-400': colorConfig.primary[400],
        'primary-500': colorConfig.primary[500],
        'primary-600': colorConfig.primary[600],
        'primary-700': colorConfig.primary[700],
        'primary-800': colorConfig.primary[800],
        'primary-900': colorConfig.primary[900],
        'neutral-50': colorConfig.neutral[50],
        'neutral-100': colorConfig.neutral[100],
        'neutral-200': colorConfig.neutral[200],
        'neutral-300': colorConfig.neutral[300],
        'neutral-400': colorConfig.neutral[400],
        'neutral-500': colorConfig.neutral[500],
        'neutral-600': colorConfig.neutral[600],
        'neutral-700': colorConfig.neutral[700],
        'neutral-800': colorConfig.neutral[800],
        'neutral-900': colorConfig.neutral[900],
        success: colorConfig.semantic.success,
        warning: colorConfig.semantic.warning,
        error: colorConfig.semantic.error,
        information: colorConfig.semantic.information,
        link: colorConfig.semantic.link,
        'information-bg': colorConfig.semantic.informationBG,
        toggle: colorConfig.semantic.toggleOn,
        'success-bg': colorConfig.semantic.successBG,
        notice: colorConfig.semantic.notice,
        'warning-bg': colorConfig.semantic.warningBG,
        'error-dark': colorConfig.semantic.errorDark,
        'notice-bg': colorConfig.semantic.noticeBG,
        'error-bg': colorConfig.semantic.errorBG,

        'rsa-secondary-dark': colorConfig.rsa.secondaryDark,
        'rsa-secondary-light': colorConfig.rsa.secondaryLight,
        'rsa-primary-dark': colorConfig.rsa.primaryDark,
        'rsa-primary-lIGHT': colorConfig.rsa.primaryLIGHT,
        'alice-blue': colorConfig.COLORS_NAME.ALICE_BLUE,
        'water-blue': colorConfig.COLORS_NAME.WATER_BLUE,
        'diamond-blue': colorConfig.COLORS_NAME.DIAMOND_BLUE,
        'pale-blue': colorConfig.COLORS_NAME.PALE_BLUE,
        'picton-blue': colorConfig.COLORS_NAME.PICTON_BLUE,
        'dodger-blue': colorConfig.COLORS_NAME.DODGER_BLUE,
        'azure-blue': colorConfig.COLORS_NAME.AZURE_BLUE,
        'true-blue': colorConfig.COLORS_NAME.TRUE_BLUE,
        'sapphire-blue': colorConfig.COLORS_NAME.SAPPHIRE_BLUE,
        'yale-blue': colorConfig.COLORS_NAME.YALE_BLUE,
        lotion: colorConfig.COLORS_NAME.LOTION,
        cultured: colorConfig.COLORS_NAME.CULTURED,
        platinum: colorConfig.COLORS_NAME.PLATINUM,
        'light-grey': colorConfig.COLORS_NAME.LIGHT_GREY,
        'quick-silver': colorConfig.COLORS_NAME.QUICK_SILVER,
        'old-silver': colorConfig.COLORS_NAME.OLD_SILVER,
        nickel: colorConfig.COLORS_NAME.NICKEL,
        'davy-grey': colorConfig.COLORS_NAME.DAVY_GREY,
        'black-olive': colorConfig.COLORS_NAME.BLACK_OLIVE,
        'raisin-black': colorConfig.COLORS_NAME.RAISIN_BLACK,
        'chinese-black': colorConfig.COLORS_NAME.CHINESE_BLACK,
        crayola: colorConfig.COLORS_NAME.CRAYOLA,
        honeydew: colorConfig.COLORS_NAME.HONEYDEW,
        'american-yellow': colorConfig.COLORS_NAME.AMERICAN_YELLOW,
        'cosmic-latte': colorConfig.COLORS_NAME.COSMIC_LATTE,
        'carmine-pink': colorConfig.COLORS_NAME.CARMINE_PINK,
        'light-red': colorConfig.COLORS_NAME.LIGHT_RED,
        carnelian: colorConfig.COLORS_NAME.CARNELIAN,
        'lavender-blush': colorConfig.COLORS_NAME.LAVENDER_BLUSH,
        'dark-gumental': colorConfig.COLORS_NAME.DARK_GUMETAL,
        'cadet-blue': colorConfig.COLORS_NAME.CADET_BLUE,
        'brown-sugar': colorConfig.COLORS_NAME.BROWN_SUGAR,
        topaz: colorConfig.COLORS_NAME.TOPAZ,
        white: colorConfig.COLORS_NAME.WHITE,
        black: colorConfig.COLORS_NAME.BLACK,
      },
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
};
